"""Build station_name_map.js from station_name_map.csv.

Usage:
  python frontend_demo/build_station_name_map.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path


def station_id(i: int) -> str:
    return f"S{i + 1:03d}"


def line_name(i: int, cols: int = 23) -> str:
    row = i // cols
    return f"L{row + 1:02d}"


def ensure_template(csv_path: Path, station_count: int = 276) -> None:
    if csv_path.exists():
        return
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["station_id", "station_name", "line_name"])
        writer.writeheader()
        for i in range(station_count):
            writer.writerow(
                {
                    "station_id": station_id(i),
                    "station_name": "",
                    "line_name": line_name(i),
                }
            )


def main() -> None:
    root = Path(__file__).resolve().parent
    csv_path = root / "station_name_map.csv"
    js_path = root / "station_name_map.js"

    ensure_template(csv_path)

    mapping = {}
    rows_total = 0
    rows_loaded = 0

    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows_total += 1
            sid = str(row.get("station_id", "")).strip().upper()
            name = str(row.get("station_name", "")).strip()
            line = str(row.get("line_name", "")).strip()

            if not sid:
                continue
            if not name:
                continue

            mapping[sid] = {"name": name, "line": line}
            rows_loaded += 1

    js_body = (
        "/* Auto-generated by build_station_name_map.py. */\n"
        + "window.StationNameMap = "
        + json.dumps(mapping, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    js_path.write_text(js_body, encoding="utf-8")

    print(f"Template/Source CSV: {csv_path}")
    print(f"Output JS: {js_path}")
    print(f"Loaded mapped stations: {rows_loaded}/{rows_total}")
    if rows_loaded == 0:
        print("Tip: fill `station_name` in station_name_map.csv, then run this script again.")


if __name__ == "__main__":
    main()
